// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.6
// source: murouse/grpc_cache/v1/grpc_cache.proto

package grpccachev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Policy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttl         *durationpb.Duration `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`                                     // Cache entry lifetime. ttl == 0 -> don't expired
	ActorScoped bool                 `protobuf:"varint,2,opt,name=actor_scoped,json=actorScoped,proto3" json:"actor_scoped,omitempty"` // Whether the cache key should include the request actor
}

func (x *Policy) Reset() {
	*x = Policy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_murouse_grpc_cache_v1_grpc_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_murouse_grpc_cache_v1_grpc_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_murouse_grpc_cache_v1_grpc_cache_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Policy) GetActorScoped() bool {
	if x != nil {
		return x.ActorScoped
	}
	return false
}

var file_murouse_grpc_cache_v1_grpc_cache_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Policy)(nil),
		Field:         51236,
		Name:          "murouse.grpc_cache.v1.policy",
		Tag:           "bytes,51236,opt,name=policy",
		Filename:      "murouse/grpc_cache/v1/grpc_cache.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional murouse.grpc_cache.v1.Policy policy = 51236;
	E_Policy = &file_murouse_grpc_cache_v1_grpc_cache_proto_extTypes[0]
)

var File_murouse_grpc_cache_v1_grpc_cache_proto protoreflect.FileDescriptor

var file_murouse_grpc_cache_v1_grpc_cache_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x58, 0x0a, 0x06, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x2b, 0x0a, 0x03, 0x74,
	0x74, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x64, 0x3a, 0x57, 0x0a, 0x06, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa4, 0x90, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x06, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x75,
	0x72, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x63, 0x61, 0x63, 0x68, 0x65, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_murouse_grpc_cache_v1_grpc_cache_proto_rawDescOnce sync.Once
	file_murouse_grpc_cache_v1_grpc_cache_proto_rawDescData = file_murouse_grpc_cache_v1_grpc_cache_proto_rawDesc
)

func file_murouse_grpc_cache_v1_grpc_cache_proto_rawDescGZIP() []byte {
	file_murouse_grpc_cache_v1_grpc_cache_proto_rawDescOnce.Do(func() {
		file_murouse_grpc_cache_v1_grpc_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_murouse_grpc_cache_v1_grpc_cache_proto_rawDescData)
	})
	return file_murouse_grpc_cache_v1_grpc_cache_proto_rawDescData
}

var file_murouse_grpc_cache_v1_grpc_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_murouse_grpc_cache_v1_grpc_cache_proto_goTypes = []any{
	(*Policy)(nil),                     // 0: murouse.grpc_cache.v1.Policy
	(*durationpb.Duration)(nil),        // 1: google.protobuf.Duration
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_murouse_grpc_cache_v1_grpc_cache_proto_depIdxs = []int32{
	1, // 0: murouse.grpc_cache.v1.Policy.ttl:type_name -> google.protobuf.Duration
	2, // 1: murouse.grpc_cache.v1.policy:extendee -> google.protobuf.MethodOptions
	0, // 2: murouse.grpc_cache.v1.policy:type_name -> murouse.grpc_cache.v1.Policy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_murouse_grpc_cache_v1_grpc_cache_proto_init() }
func file_murouse_grpc_cache_v1_grpc_cache_proto_init() {
	if File_murouse_grpc_cache_v1_grpc_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_murouse_grpc_cache_v1_grpc_cache_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Policy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_murouse_grpc_cache_v1_grpc_cache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_murouse_grpc_cache_v1_grpc_cache_proto_goTypes,
		DependencyIndexes: file_murouse_grpc_cache_v1_grpc_cache_proto_depIdxs,
		MessageInfos:      file_murouse_grpc_cache_v1_grpc_cache_proto_msgTypes,
		ExtensionInfos:    file_murouse_grpc_cache_v1_grpc_cache_proto_extTypes,
	}.Build()
	File_murouse_grpc_cache_v1_grpc_cache_proto = out.File
	file_murouse_grpc_cache_v1_grpc_cache_proto_rawDesc = nil
	file_murouse_grpc_cache_v1_grpc_cache_proto_goTypes = nil
	file_murouse_grpc_cache_v1_grpc_cache_proto_depIdxs = nil
}
